name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into GCE VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_PRIVATE_KEY }}
          port: ${{ secrets.GCE_SSH_PORT }}
          script: |
            # Run deployment script on GCE VM
            cd ~/atama
            git pull origin main
            # Additional deployment steps (e.g., build, restart Nginx)

