name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

#    services:
#      mysql:
#        image: mysql:8.0
#        env:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: laravel
#          MYSQL_USER: laravel
#          MYSQL_PASSWORD: secret
#        ports:
#          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-scripts --no-interaction

#      - name: Generate application key
#        run: php artisan key:generate

#      - name: Run database migrations
#        run: php artisan migrate --env=testing --no-interaction

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install NPM dependencies
        run: npm install

      - name: Run NPM build script
        run: npm run dev

      - name: Run PHPUnit tests
        run: php artisan test
